name = "EnviousMC"
author = "EnviousLabs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1202ab80ee1ed5e01e9f103a01a70905ca3a8db3a87b3476aa8109dbfb4c6945"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
